### ISSUE TITLE
Difference between DSBN and AdaBN

### ISSUE THREAD

**Issue by semi-supervised-paper** [wgchang/DSBN#4]
Hi,
After reading the paper, I am still puzzled about the difference between DSBN and AdaBN. I think the main difference between DSBN and AdaBN is an additional pseudo label loss in DSBN. However, I can't find the experiment results comparing DSBN and AdaBN in the paper. Have you reproduced AdaBN in your experiments?
Thanks.

**Comment by wgchang** [comment]
The main difference is that AdaBN doesn't have separate affine parameters for each domain and DSBN follows moving average scheme of BN paper. AdaBN propose a new online algorithm to estimate the mean and variance of BN layer, which is different from common moving update scheme. While, DSBN follow moving average scheme of BN paper to update mean and variance and have separate affine parameters for each domain.
When we wrote the paper, the source code of AdaBN was not available, so we couldn't verify the source code and reproduce it.

**Comment by woozch** [comment]
To add more to the differences you mentioned, the main difference is that AdaBN doesn't have separate affine parameters for each domain. DSBN has separate affine parameters for each domain. 
Also, AdaBN propose a online algorithm to re-estimate the mean and variance of BN layer for target domain, which is different from the common moving update scheme. The algorithm simply re-estimates batch mean and variance on the target domain, while DSBN jointly updates batch statistics(mean and variance) using moving average scheme of BN paper during training.
When we wrote the paper, the source code of AdaBN was not available, so we couldn't verify the source code and reproduce it. Also, they didn't use ResNet and didn't provide experimental results on VisDA dataset.
