### ISSUE TITLE
One problem

### ISSUE THREAD

**Issue by BX-xb** [wgchang/DSBN#9]
Hello~ Thank you for your excellent work. I have a question.
In the result of multiple source domain (merged and separate) in your paper,  what is the difference between BN and DSBN when the Domain is separated, do you design the same number of  branch for BN , how to do BN in the separate case?

**Comment by woozch** [comment]
BN indicates that the BN layer is shared by both the source and target datasets. On the other hand, DSBN means that there are separate BN layers for source and target, and each layer is learned separately. 
In the case of multiple sources, it means that each source has a separate BN.
For example, in the case of "separate", if there are 2 sources and 1 target, there are 3 BN layers.
In the case of "merged", if there are 2 sources and 1 target, 2 sources are considered as one source and there are 2 BN layers in total.

**Comment by BX-xb** [comment]
Thank you for your reply.  In the separate case of your example, the number of branch is 3, same for BN and DSBN. Why the result of BN and DSBN is different for the Table3?

**Comment by woozch** [comment]
No. In the separate case of your example, the number of BN branches is not the same for BN and DSBN. 
For example, Table3 in the paper, 
A->W : 
    BN: one BN
    DSBN: two BN (1 source, 1 target)
(A+D)->W: [two sources are merged into one and considered as a new dataset]
    BN: one BN
    DSBN: two BN (1 source, 1 target)
A, D -> W: [two sources and one target are inferenced with different batch construction]
    BN: one BN
    DSBN: three BN (2 sources, 1 target)
